version: '3.8'

services:
  db:
    image: postgis/postgis
    container_name: praktikum
    restart: always
    environment:
      POSTGRES_DB: praktikum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5002:5432'
    # Mount a volume named local_pgdata to /var/lib/postgresql/data inside the container
    volumes:
      - local_pgdata:/var/lib/postgresql/data

# Define a named volume local_pgdata
volumes:
  local_pgdata:
  # You can add additional options here, like driver or size (refer to Docker Compose documentation for details)
